/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_melp_Quickjs */

#ifndef _Included_nl_melp_Quickjs
#define _Included_nl_melp_Quickjs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_melp_Quickjs
 * Method:    eval
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_nl_melp_Quickjs_eval
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
